[package]
name = "human-sort"
version = "0.1.6"
authors = ["Vlad Nagikh <paradakh@protonmail.com>"]
license = "MIT"
license-file = 'LICENSE'
repository = "https://github.com/vladnagih/human-sort"
description = "Human sort (natural sort) implementation"
keywords = ["sort", "natural", "human", "order"]
readme = "README.md"
edition = "2018"

[dependencies]
